2017-12-11 11:16:23,658 - teradata.udaexec - INFO - Initializing UdaExec...
2017-12-11 11:16:23,658 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/home/users/hibellm/udaexec.ini: Found', '/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/udaexec.ini: Not Found']
2017-12-11 11:16:23,658 - teradata.udaexec - INFO - No previous run number found as /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/.runNumber does not exist. Initializing run number to 1
2017-12-11 11:16:23,658 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2017-12-11 11:16:23,658 - teradata.udaexec - INFO - Removed 0 log files.
2017-12-11 11:16:23,695 - teradata.udaexec - INFO - Checkpoint file not found: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/HelloWorld.checkpoint
2017-12-11 11:16:23,696 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2017-12-11 11:16:23,696 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20171211111623-1
 *             Host: rkaustms02
 *         Platform: Linux-3.0.101-0.125.TDC.1.R.0-default-x86_64-with-SuSE-11-x86_64
 *          OS User: hibellm
 *   Python Version: 3.5.1
 *  Python Compiler: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
 *     Python Build: ('default', 'Jun 15 2016 15:32:45')
 *  UdaExec Version: 15.10.0.16
 *     Program Name: td_python.py
 *      Working Dir: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp
 *      Git Version: git version 2.10.2
 *     Git Revision: 195a97f
 *        Git Dirty: True [ M README.md, M app.py, M app_tdcon.py, M data.py, M listfiles1.txt, M listfiles2.txt, M osscript.py, M td_python.py, M td_python_connection.py, M templates/about.html, M templates/add_datasource.html, M templates/add_vendor.html, M templates/dashboard.html, M templates/dashboardd.html, M templates/dashboardv.html, M templates/datasource.html, M templates/datasources.html, M templates/edit_datasource.html, M templates/edit_vendor.html, M templates/home.html, M templates/includes/_formhelpers.html, M templates/includes/_messages.html, M templates/includes/_navbar.html, M templates/layout.html, M templates/login.html, M templates/register.html, M templates/roles.html, M templates/ru_datasource.html, M templates/shell.html, M templates/tablesort.js, M templates/vendor.html, M templates/vendors.html, M templates/vendors_tdcon.html,?? .runNumber,?? logs/]
 *          Log Dir: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs
 *         Log File: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs/HelloWorld.20171211111623-1.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/home/users/hibellm/udaexec.ini: Found', '/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20171211111623-1;ClientUser=hibellm;Production=False;udaAppLogFile=/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs/HelloWorld.20171211111623-1.log;gitRevision=195a97f;gitDirty=True;UtilityName=PyTd;UtilityVersion=15.10.0.16
********************************************************************************/
2017-12-11 11:16:23,697 - teradata.udaexec - INFO - Creating connection: {'username': 'hibellm', 'method': 'odbc', 'system': 'rochetd', 'password': 'XXXXXX'}
2017-12-11 11:16:23,697 - teradata.tdodbc - INFO - Loading ODBC Library: libodbc.so
2017-12-11 11:16:23,851 - teradata.udaexec - INFO - Connection successful. Duration: 0.154 seconds. Details: {'username': 'hibellm', 'method': 'odbc', 'system': 'rochetd', 'password': 'XXXXXX'}
2017-12-11 11:16:23,880 - teradata.udaexec - INFO - Query Successful. Duration: 0.029 seconds, Rows: 1, Query: SELECT GetQueryBand()
2017-12-11 11:16:23,884 - teradata.udaexec - INFO - Initializing UdaExec...
2017-12-11 11:16:23,884 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/home/users/hibellm/udaexec.ini: Found', '/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/udaexec.ini: Not Found']
2017-12-11 11:16:23,884 - teradata.udaexec - INFO - Found run number file: "/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/.runNumber"
2017-12-11 11:16:23,884 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2017-12-11 11:16:23,884 - teradata.udaexec - INFO - Removed 0 log files.
2017-12-11 11:16:23,900 - teradata.udaexec - INFO - Checkpoint file not found: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/FlaskApp.checkpoint
2017-12-11 11:16:23,900 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2017-12-11 11:16:23,900 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: FlaskApp
 *          Version: 1
 *       Run Number: 20171211111623-2
 *             Host: rkaustms02
 *         Platform: Linux-3.0.101-0.125.TDC.1.R.0-default-x86_64-with-SuSE-11-x86_64
 *          OS User: hibellm
 *   Python Version: 3.5.1
 *  Python Compiler: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
 *     Python Build: ('default', 'Jun 15 2016 15:32:45')
 *  UdaExec Version: 15.10.0.16
 *     Program Name: td_python.py
 *      Working Dir: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp
 *      Git Version: git version 2.10.2
 *     Git Revision: 195a97f
 *        Git Dirty: True [ M README.md, M app.py, M app_tdcon.py, M data.py, M listfiles1.txt, M listfiles2.txt, M osscript.py, M td_python.py, M td_python_connection.py, M templates/about.html, M templates/add_datasource.html, M templates/add_vendor.html, M templates/dashboard.html, M templates/dashboardd.html, M templates/dashboardv.html, M templates/datasource.html, M templates/datasources.html, M templates/edit_datasource.html, M templates/edit_vendor.html, M templates/home.html, M templates/includes/_formhelpers.html, M templates/includes/_messages.html, M templates/includes/_navbar.html, M templates/layout.html, M templates/login.html, M templates/register.html, M templates/roles.html, M templates/ru_datasource.html, M templates/shell.html, M templates/tablesort.js, M templates/vendor.html, M templates/vendors.html, M templates/vendors_tdcon.html,?? .runNumber,?? logs/]
 *          Log Dir: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs
 *         Log File: /data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs/FlaskApp.20171211111623-2.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/home/users/hibellm/udaexec.ini: Found', '/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=FlaskApp;Version=1;JobID=20171211111623-2;ClientUser=hibellm;Production=False;udaAppLogFile=/data/RWD_SHARE/MDH/users/hibellm/flask/ruflaskapp/logs/FlaskApp.20171211111623-2.log;gitRevision=195a97f;gitDirty=True;UtilityName=PyTd;UtilityVersion=15.10.0.16
********************************************************************************/
2017-12-11 11:16:23,901 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "td_python.py", line 17, in <module>
    with udaExec.connect("${dataSourceName}") as session:
  File "/opt/anaconda3/lib/python3.5/site-packages/teradata-15.10.0.16-py3.5.egg/teradata/udaexec.py", line 144, in connect
    args = self.config.section(externalDSN)
  File "/opt/anaconda3/lib/python3.5/site-packages/teradata-15.10.0.16-py3.5.egg/teradata/udaexec.py", line 606, in section
    (section, self.configSection))
  File "/opt/anaconda3/lib/python3.5/site-packages/teradata-15.10.0.16-py3.5.egg/teradata/udaexec.py", line 562, in resolveDict
    d[key] = self._resolve(value, sections, None, None)
  File "/opt/anaconda3/lib/python3.5/site-packages/teradata-15.10.0.16-py3.5.egg/teradata/udaexec.py", line 600, in _resolve
    "Not found: {}".format(value, error))
teradata.api.InterfaceError: ('CONFIG_ERROR', 'Unable to resolve variable "$tdwallet(username)".  Not found: \'tdwallet\'')
2017-12-11 11:16:23,902 - teradata.udaexec - INFO - UdaExec exiting.
2017-12-11 11:16:23,903 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2017-12-11 11:16:23,918 - teradata.udaexec - INFO - UdaExec exiting.
